/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TimetableIndexImport } from './routes/timetable/index'
import { Route as SettingsIndexImport } from './routes/settings/index'
import { Route as LeaderboardIndexImport } from './routes/leaderboard/index'
import { Route as FitnessIndexImport } from './routes/fitness/index'
import { Route as FinancesIndexImport } from './routes/finances/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as AcademicsIndexImport } from './routes/academics/index'
import { Route as FitnessrouteImport } from './routes/fitness/__route'
import { Route as FitnessStatTypeImport } from './routes/fitness/$statType'
import { Route as FinancesReportImport } from './routes/finances/report'
import { Route as FinancesBudgetImport } from './routes/finances/budget'
import { Route as FinancesAllImport } from './routes/finances/all'
import { Route as AcademicsCourseIndexImport } from './routes/academics/course/index'

// Create Virtual Routes

const FitnessImport = createFileRoute('/fitness')()

// Create/Update Routes

const FitnessRoute = FitnessImport.update({
  id: '/fitness',
  path: '/fitness',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TimetableIndexRoute = TimetableIndexImport.update({
  id: '/timetable/',
  path: '/timetable/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsIndexRoute = SettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRoute,
} as any)

const LeaderboardIndexRoute = LeaderboardIndexImport.update({
  id: '/leaderboard/',
  path: '/leaderboard/',
  getParentRoute: () => rootRoute,
} as any)

const FitnessIndexRoute = FitnessIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FitnessRoute,
} as any)

const FinancesIndexRoute = FinancesIndexImport.update({
  id: '/finances/',
  path: '/finances/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const AcademicsIndexRoute = AcademicsIndexImport.update({
  id: '/academics/',
  path: '/academics/',
  getParentRoute: () => rootRoute,
} as any)

const FitnessrouteRoute = FitnessrouteImport.update({
  id: '/__route',
  getParentRoute: () => FitnessRoute,
} as any)

const FitnessStatTypeRoute = FitnessStatTypeImport.update({
  id: '/fitness/$statType',
  path: '/fitness/$statType',
  getParentRoute: () => rootRoute,
} as any)

const FinancesReportRoute = FinancesReportImport.update({
  id: '/finances/report',
  path: '/finances/report',
  getParentRoute: () => rootRoute,
} as any)

const FinancesBudgetRoute = FinancesBudgetImport.update({
  id: '/finances/budget',
  path: '/finances/budget',
  getParentRoute: () => rootRoute,
} as any)

const FinancesAllRoute = FinancesAllImport.update({
  id: '/finances/all',
  path: '/finances/all',
  getParentRoute: () => rootRoute,
} as any)

const AcademicsCourseIndexRoute = AcademicsCourseIndexImport.update({
  id: '/academics/course/',
  path: '/academics/course/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/finances/all': {
      id: '/finances/all'
      path: '/finances/all'
      fullPath: '/finances/all'
      preLoaderRoute: typeof FinancesAllImport
      parentRoute: typeof rootRoute
    }
    '/finances/budget': {
      id: '/finances/budget'
      path: '/finances/budget'
      fullPath: '/finances/budget'
      preLoaderRoute: typeof FinancesBudgetImport
      parentRoute: typeof rootRoute
    }
    '/finances/report': {
      id: '/finances/report'
      path: '/finances/report'
      fullPath: '/finances/report'
      preLoaderRoute: typeof FinancesReportImport
      parentRoute: typeof rootRoute
    }
    '/fitness/$statType': {
      id: '/fitness/$statType'
      path: '/fitness/$statType'
      fullPath: '/fitness/$statType'
      preLoaderRoute: typeof FitnessStatTypeImport
      parentRoute: typeof rootRoute
    }
    '/fitness': {
      id: '/fitness'
      path: '/fitness'
      fullPath: '/fitness'
      preLoaderRoute: typeof FitnessImport
      parentRoute: typeof rootRoute
    }
    '/fitness/__route': {
      id: '/fitness/__route'
      path: '/fitness'
      fullPath: '/fitness'
      preLoaderRoute: typeof FitnessrouteImport
      parentRoute: typeof FitnessRoute
    }
    '/academics/': {
      id: '/academics/'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/finances/': {
      id: '/finances/'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof FinancesIndexImport
      parentRoute: typeof rootRoute
    }
    '/fitness/': {
      id: '/fitness/'
      path: '/'
      fullPath: '/fitness/'
      preLoaderRoute: typeof FitnessIndexImport
      parentRoute: typeof FitnessImport
    }
    '/leaderboard/': {
      id: '/leaderboard/'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexImport
      parentRoute: typeof rootRoute
    }
    '/timetable/': {
      id: '/timetable/'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableIndexImport
      parentRoute: typeof rootRoute
    }
    '/academics/course/': {
      id: '/academics/course/'
      path: '/academics/course'
      fullPath: '/academics/course'
      preLoaderRoute: typeof AcademicsCourseIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface FitnessRouteChildren {
  FitnessrouteRoute: typeof FitnessrouteRoute
  FitnessIndexRoute: typeof FitnessIndexRoute
}

const FitnessRouteChildren: FitnessRouteChildren = {
  FitnessrouteRoute: FitnessrouteRoute,
  FitnessIndexRoute: FitnessIndexRoute,
}

const FitnessRouteWithChildren =
  FitnessRoute._addFileChildren(FitnessRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/finances/all': typeof FinancesAllRoute
  '/finances/budget': typeof FinancesBudgetRoute
  '/finances/report': typeof FinancesReportRoute
  '/fitness/$statType': typeof FitnessStatTypeRoute
  '/fitness': typeof FitnessrouteRoute
  '/academics': typeof AcademicsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/finances': typeof FinancesIndexRoute
  '/fitness/': typeof FitnessIndexRoute
  '/leaderboard': typeof LeaderboardIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/timetable': typeof TimetableIndexRoute
  '/academics/course': typeof AcademicsCourseIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/finances/all': typeof FinancesAllRoute
  '/finances/budget': typeof FinancesBudgetRoute
  '/finances/report': typeof FinancesReportRoute
  '/fitness/$statType': typeof FitnessStatTypeRoute
  '/fitness': typeof FitnessIndexRoute
  '/academics': typeof AcademicsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/finances': typeof FinancesIndexRoute
  '/leaderboard': typeof LeaderboardIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/timetable': typeof TimetableIndexRoute
  '/academics/course': typeof AcademicsCourseIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/finances/all': typeof FinancesAllRoute
  '/finances/budget': typeof FinancesBudgetRoute
  '/finances/report': typeof FinancesReportRoute
  '/fitness/$statType': typeof FitnessStatTypeRoute
  '/fitness': typeof FitnessRouteWithChildren
  '/fitness/__route': typeof FitnessrouteRoute
  '/academics/': typeof AcademicsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/finances/': typeof FinancesIndexRoute
  '/fitness/': typeof FitnessIndexRoute
  '/leaderboard/': typeof LeaderboardIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/timetable/': typeof TimetableIndexRoute
  '/academics/course/': typeof AcademicsCourseIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/finances/all'
    | '/finances/budget'
    | '/finances/report'
    | '/fitness/$statType'
    | '/fitness'
    | '/academics'
    | '/dashboard'
    | '/finances'
    | '/fitness/'
    | '/leaderboard'
    | '/settings'
    | '/timetable'
    | '/academics/course'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/finances/all'
    | '/finances/budget'
    | '/finances/report'
    | '/fitness/$statType'
    | '/fitness'
    | '/academics'
    | '/dashboard'
    | '/finances'
    | '/leaderboard'
    | '/settings'
    | '/timetable'
    | '/academics/course'
  id:
    | '__root__'
    | '/'
    | '/finances/all'
    | '/finances/budget'
    | '/finances/report'
    | '/fitness/$statType'
    | '/fitness'
    | '/fitness/__route'
    | '/academics/'
    | '/dashboard/'
    | '/finances/'
    | '/fitness/'
    | '/leaderboard/'
    | '/settings/'
    | '/timetable/'
    | '/academics/course/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinancesAllRoute: typeof FinancesAllRoute
  FinancesBudgetRoute: typeof FinancesBudgetRoute
  FinancesReportRoute: typeof FinancesReportRoute
  FitnessStatTypeRoute: typeof FitnessStatTypeRoute
  FitnessRoute: typeof FitnessRouteWithChildren
  AcademicsIndexRoute: typeof AcademicsIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  FinancesIndexRoute: typeof FinancesIndexRoute
  LeaderboardIndexRoute: typeof LeaderboardIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TimetableIndexRoute: typeof TimetableIndexRoute
  AcademicsCourseIndexRoute: typeof AcademicsCourseIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinancesAllRoute: FinancesAllRoute,
  FinancesBudgetRoute: FinancesBudgetRoute,
  FinancesReportRoute: FinancesReportRoute,
  FitnessStatTypeRoute: FitnessStatTypeRoute,
  FitnessRoute: FitnessRouteWithChildren,
  AcademicsIndexRoute: AcademicsIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  FinancesIndexRoute: FinancesIndexRoute,
  LeaderboardIndexRoute: LeaderboardIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TimetableIndexRoute: TimetableIndexRoute,
  AcademicsCourseIndexRoute: AcademicsCourseIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/finances/all",
        "/finances/budget",
        "/finances/report",
        "/fitness/$statType",
        "/fitness",
        "/academics/",
        "/dashboard/",
        "/finances/",
        "/leaderboard/",
        "/settings/",
        "/timetable/",
        "/academics/course/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/finances/all": {
      "filePath": "finances/all.tsx"
    },
    "/finances/budget": {
      "filePath": "finances/budget.tsx"
    },
    "/finances/report": {
      "filePath": "finances/report.tsx"
    },
    "/fitness/$statType": {
      "filePath": "fitness/$statType.tsx"
    },
    "/fitness": {
      "filePath": "fitness",
      "children": [
        "/fitness/__route",
        "/fitness/"
      ]
    },
    "/fitness/__route": {
      "filePath": "fitness/__route.tsx",
      "parent": "/fitness"
    },
    "/academics/": {
      "filePath": "academics/index.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/finances/": {
      "filePath": "finances/index.tsx"
    },
    "/fitness/": {
      "filePath": "fitness/index.tsx",
      "parent": "/fitness"
    },
    "/leaderboard/": {
      "filePath": "leaderboard/index.tsx"
    },
    "/settings/": {
      "filePath": "settings/index.tsx"
    },
    "/timetable/": {
      "filePath": "timetable/index.tsx"
    },
    "/academics/course/": {
      "filePath": "academics/course/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
